### ISSUE TITLE
Slowmode Management (for #sensitive-topics)

### ISSUE THREAD

**Issue by ceSchueler** [Arborym/Pax-Academia#112]
Pax should monitor activity in a channel and should be able to change slowmode based on activity, number of users, or a schedule.

- [ ] Monitor #sensitive-topics activity (perhaps in DB)
- [ ] -->(Query) How many messages have been sent in the past 20 minutes.
- [ ] -->(Query) How many messages have been sent in the past 20 minutes.
- [ ] -->(Query) Any other metric that might be useful

- [ ] Command to set slowmode lower and upper range `/slowmode range <range-min> <range-max>` (max range would be _OFF_ to _6h_)

- [ ] Command to schedule slowmode: `/slowmode schedule <slowmode-mode [OFF-6h]> <duration active>* <start-delay>`
\*should return to default after duration. `<start-delay>` is an optional parameter everything else should be required.

- [ ] Command to set default slow mode: `/slowmode default <mode>*`
\* Modes: OFF (no slowmode), no-interact (Pax does nothing), auto (Pax does stuff).

- [ ] Command to set current slow mode: `/slowmode mode <mode>` (modes described above)

Optional:
- [ ] Command to set criteria for "Auto" mode to increase slowmode
- [ ] Command to set criteria for "Auto" mode to decrease slowmode

**Comment by sebastiaan-daniels** [comment]
Stale Issue (Untouched since April), is this still needed?

**Comment by sebastiaan-daniels** [comment]
Closed as discussed [here](https://discord.com/channels/238956364729155585/1040360228388098159/1120794553050472468)
