### ISSUE TITLE
[Alerts] Further customisation of Alerts.

### ISSUE THREAD

**Issue by ceSchueler** [Arborym/Pax-Academia#119]
- [ ] Ability to set list of ignored channel (categories)
- [ ] Ability to set list of ignored roles
- [ ] Ability to set list of ignored users (at least ignore self as an option)
- [x] Ability to pause/suspend alerts for a period of time

Questionable if we should implement or not:
- [ ] Above abilities, but whitelist instead of blacklist (setting target channels, target roles, target users)

**Comment by sebastiaan-daniels** [comment]
This is a stale issue.
Please re-open if still important.
