### ISSUE TITLE
/see-apps improvements

### ISSUE THREAD

**Issue by ceSchueler** [Arborym/Pax-Academia#162]
- [x] Change `/see-apps subcommand:spam` to match all other subcommands in appearance (when empty).
- [x]  Remove introductory embed (before clicking ➡️ after using `see-apps`) instead **introduce dummy command** with example applications.
    - [x] Dummy command should mirror real command, only differentiated by prefix `dummy-` and manipulating test-data
    - [x] Dummy command should have at least one application in every possible state
    - [x] Dummy command should reset to original test data with subcommand
    - [x] [Optional] Dummy entries should detail what to be done with them i.e. by putting "Mark me as Spam" in the name field.
    - [x] [Optional] Dummy entries should include instructions / what is expected to happen, or how to undo an action

Renaming:
- [x] Rename `Applicant name` &rarr; `Applicant Name`
- [x] Rename `first name` &rarr; `First Name`
- [x] Rename `Second Opinion required` &rarr; `Second Opinion Required`
- [x] Rename `Time zone` &rarr; `Time Zone`
- [x] Rename `Hours available per week` &rarr; `Hours Available per Week`
- [x] Rename `Why staff?` &rarr; `Why do you want to become a staff member?`
- [x] Rename `Why do you want to become a staff member` &rarr; `Why do you want to become a staff member?`
- [x] Rename `Contribute reason` &rarr; `How will you contribute if you become a staff member?`
- [x] Rename `How can you contribute if you are given staff` &rarr; `How will you contribute if you become a staff member?`
- [x] Rename `Submission time` &rarr; `Submission Time`
- [x] Rename `Like / Dislikes` &rarr; `Likes / Dislikes`

If introductory embed is not removed generally:
- [x] Remove introductory embed when using `/see-apps specific_id`

Consider:
- [x] Renaming `/see-apps` into `/see-applications` OR `/see-sapps` (see _staff_ apps)
- [x] Introducing subcommand `list` in command to group options `all`, `spam` `accepted` `denied`

Might have some more when the dummy command is here, since we now only have a real application now and I can't test anymore...

**Comment by sebastiaan-daniels** [comment]
Dummy command seems like a bad idea in a production environment.. I recommend staff members to read the instructions instead of adding a whole new, resettable command.

**Comment by sebastiaan-daniels** [comment]
1) Won't fix: the moment you have >1 spam this issue is gone forever
2) Won't implement: Dummy command is a dumb idea
3) Renaming: In progress

(Will update this comment when more work is done)
