### ISSUE TITLE
Create `AutoDeletionDetection.py`

### ISSUE THREAD

**Issue by Arborym** [Arborym/Pax-Academia#205]
Required by staff team: Create a system that detects user messages being deleted in quick succession.

- Should generate a report showing messages deleted in the last hour, every hour, in increments of ten minutes.
- Determine control limits for anomaly criteria
- When the algorithm detects that a user surpasses the control limit, their roles will be cached, and the user will be muted
- Create a button that allows staff to unmute the individual in cases of false positives

**Comment by sebastiaan-daniels** [comment]
Are we talking about people deleting other people's messages (in which case all good),
or do we talk about people who delete their own messages?

Because in the latter case, people have the right to be forgotten, and the right to delete their content.
(GDPR articles 17 & 19)

**Comment by Arborym** [comment]
Hi, @woseek. Would you be able to provide more information about this system in this issue thread so that everyone is on the same page? Thanks!
