### ISSUE TITLE
Add ability to give feedback on experimental commands

### ISSUE THREAD

**Issue by sebastiaan-daniels** [Arborym/Pax-Academia#219]
As Pax commands start becoming more experimental, and a little more invasive with on_message events, Some commands that are in early production might give false positives/be sent incorrectly.

An easy way to decorate a command as experimental should be created to ask active, verified members of the community to share their feedback with experimental commands. This feedback will be stored in the database and will be used by developers to evaluate their code before making it invasive/forced

**Comment by pharmony01** [comment]
Discussion relating to this feature happened here https://discord.com/channels/238956364729155585/791697255835893821/1139453976719405206
