### ISSUE TITLE
Type Refactoring

### ISSUE THREAD

**Issue by Arborym** [Arborym/Pax-Academia#223]
A lot of functions, methods, and variables are typed incorrectly throughout the project. This issue serves as a tracker for correcting those types.

The incorrect types can cause a number of problems, including:

- Errors when the code is run.
- Difficulties in debugging the code.
- Difficulties in understanding the code.

This issue should be fixed to improve the quality of the code and to make it more maintainable.

**Comment by GabeMillikan** [comment]
I will be opening several refactor-PRs in the following weeks :)

**Comment by GabeMillikan** [comment]
Not completed yet, still needs #229 to do fix the actual typing.
