### ISSUE TITLE
Self-inflicted Pax alert

### ISSUE THREAD

**Issue by pharmony01** [Arborym/Pax-Academia#231]
Not sure if this has been talked about, but I would think you shouldn't be able to get an alert from your own message. I already know that I said it, so it doesn't benefit me to get a ping for it.

**Comment by Arborym** [comment]
I remember there was discussion surrounding this a while ago, and we decided to keep it in for testing purposes. When we were first building out the cog, the most efficient way to test alerts was to trigger them ourselves.
