### ISSUE TITLE
Make #tutor-logs keywords dynamically editable via slash command

### ISSUE THREAD

**Issue by MountainAero** [Arborym/Pax-Academia#30]
Move filter word list in separate file for alerts.

**Comment by Arborym** [comment]
Create a slash command `/add-tutor-keywords` in the file `Alerts.py` that takes a str as an input, and appends it to a DB of keywords. Staff should be able to use this slash command to add tutor-related keywords to track in the #tutor-logs channel.

**Comment by MountainAero** [comment]
First implementation committed, please test

**Comment by Arborym** [comment]
Tutor logging has been removed, closing issue
