### ISSUE TITLE
Staff application command [SAC] stage 2

### ISSUE THREAD

**Issue by ceSchueler** [Arborym/Pax-Academia#53]
Builds on #41  : Additionally SAC should check if the user has
- [ ]  At least 500 messages in _any_ channel.

Also optionally:
- [ ]  Send `?modlogs` log of user in #google-form-submissions channel automatically upon (valid*) received application.
     - Wouldn't work if someone submitted a troll application.
     - Shouldn't work with staff account names.

**Comment by sebastiaan-daniels** [comment]
Message logging (at least 500) will be stored in db. (see issue #45 )

**Comment by MountainAero** [comment]
Depends on another feature to be implemented first: https://github.com/Arborym/Pax-Academia/issues/45

**Comment by MountainAero** [comment]
Regarding point 2: This shouldn't be an issue since we know the uID of the invoking user. A user can only create an application for themselves. There is no possibility for a user to enter another user's uID
