### ISSUE TITLE
Rename /ask and make it anonymous

### ISSUE THREAD

**Issue by GabeMillikan** [Arborym/Pax-Academia#93]
There are two issues with our current /ask command:
1. Sometimes, users think that that is the command to ask a question. So they do `/ask What's 2+2?`, then never get a response.
2. It isn't anonymous, so whoever uses the command will almost assuredly be pinged once the user finally does ask their question. Just because I want the user to ask their question, doesn't mean I want to commit to answering it.
> Me: /ask
> Bot: @gabe used the /ask command: ask your question
> Them: Okay what is 2 + 2?
> Them: @gabe why aren't you answering my question?

Related to [this thread](https://discord.com/channels/238956364729155585/1047785196063309835/1048956051283791943) in Discord

**Comment by sebastiaan-daniels** [comment]
Correct me if I'm wrong, but I think /ask is part of the HWH bot, not the Pax  Academia bot.

**Comment by GabeMillikan** [comment]
Oh @sebastiaan-daniels you're totally right haha, I [blame rust](https://discord.com/channels/238956364729155585/1047785196063309835/1048956051283791943)
