### ISSUE TITLE
Allow mass-muting and -kicking of users

### ISSUE THREAD

**Issue by MountainAero** [Arborym/Pax-Academia#98]
Especially in raid situations outright banning all accounts which joined during a certain time will inevitably lead to a small number of false positives. Having available a possibility to mass-mute and mass-kick suspected accounts allows legit users to come back and ask to be unmuted.

In order to streamline this process, both a command /mmute for mass-muting and /mkick for mass-kicking as well as a combination of both, /mmutekick that first mutes and then kicks all users could be implemented. The syntax of the command should be compatible with the one used for Aperture at the moment.

**Comment by sebastiaan-daniels** [comment]
Closing as discussed [here](https://discord.com/channels/238956364729155585/1040360228388098159/1120794553050472468)
